<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalog-report.xsl"?>
<!-- Complete XSLT 3.0 report with XML, XPath-like attributes, and Unicode. -->
<xsl:stylesheet version="3.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:cat="urn:example:catalog"
  xmlns:r="urn:example:report"
  xmlns:f="urn:example:functions"
  xmlns:map="http://www.w3.org/2005/xpath-functions/map"
  exclude-result-prefixes="xs cat f map">

  <xsl:output method="xml"
    encoding="UTF-8"
    indent="yes"
    omit-xml-declaration="no"/>

  <xsl:strip-space elements="*"/>
  <xsl:mode name="detail" on-no-match="shallow-skip"/>
  <xsl:mode name="summary" on-no-match="shallow-copy"/>

  <xsl:param name="minimum-price" as="xs:decimal" select="0"/>
  <xsl:param name="maximum-price" as="xs:decimal" select="9999"/>
  <xsl:param name="preferred-language" as="xs:string" select="'en'"/>
  <xsl:param name="include-hidden" as="xs:boolean" select="false()"/>

  <xsl:variable name="currency-symbols" as="map(xs:string, xs:string)"
    select="map { 'EUR': '€', 'USD': '$', 'JPY': '¥' }"/>
  <xsl:variable name="unicode-sample" select="'BMP λ 東京; astral 🚀 𝌆'"/>

  <xsl:key name="category-by-code" match="cat:category" use="@code"/>
  <xsl:key name="item-by-id" match="cat:item" use="@id"/>

  <xsl:function name="f:display-price" as="xs:string">
    <xsl:param name="item" as="element(cat:item)"/>
    <xsl:variable name="code" select="string($item/@currency)"/>
    <xsl:variable name="symbol" select="($currency-symbols($code), $code)[1]"/>
    <xsl:sequence select="concat($symbol, format-number(xs:decimal($item/@price), '0.00'))"/>
  </xsl:function>

  <xsl:function name="f:is-visible" as="xs:boolean">
    <xsl:param name="item" as="element(cat:item)"/>
    <xsl:sequence select="$include-hidden or not($item/@hidden = 'true')"/>
  </xsl:function>

  <xsl:template match="/">
    <xsl:apply-templates select="cat:catalog"/>
  </xsl:template>

  <xsl:template match="cat:catalog">
    <r:report xml:lang="{$preferred-language}">
      <xsl:namespace name="meta" select="'urn:example:metadata'"/>
      <xsl:attribute name="generated-at" select="current-dateTime()"/>
      <xsl:attribute name="source-version" select="(@version, 'unknown')[1]"/>

      <r:title>
        <xsl:value-of select="(cat:title[@xml:lang = $preferred-language], cat:title)[1]"/>
      </r:title>

      <r:unicode>
        <xsl:value-of select="$unicode-sample"/>
      </r:unicode>

      <xsl:call-template name="summary">
        <xsl:with-param name="items" select="cat:items/cat:item"/>
      </xsl:call-template>

      <r:categories>
        <xsl:apply-templates select="cat:categories/cat:category" mode="summary">
          <xsl:sort select="lower-case(cat:name)"/>
        </xsl:apply-templates>
      </r:categories>

      <r:items>
        <xsl:apply-templates
          select="cat:items/cat:item[f:is-visible(.)][xs:decimal(@price) ge $minimum-price][xs:decimal(@price) le $maximum-price]"
          mode="detail">
          <xsl:sort select="@category"/>
          <xsl:sort select="lower-case(cat:name)"/>
        </xsl:apply-templates>
      </r:items>

      <xsl:comment>Generated by the grammar stress fixture; all tags close.</xsl:comment>
    </r:report>
  </xsl:template>

  <xsl:template name="summary">
    <xsl:param name="items" as="element(cat:item)*"/>
    <r:summary>
      <r:total>
        <xsl:value-of select="count($items)"/>
      </r:total>
      <r:visible>
        <xsl:value-of select="count($items[f:is-visible(.)])"/>
      </r:visible>
      <r:average-price>
        <xsl:value-of
          select="if (exists($items)) then format-number(avg($items/@price ! xs:decimal(.)), '0.00') else '0.00'"/>
      </r:average-price>
      <r:range minimum="{$minimum-price}" maximum="{$maximum-price}"/>
    </r:summary>
  </xsl:template>

  <xsl:template match="cat:category" mode="summary">
    <r:category code="{@code}">
      <xsl:attribute name="items" select="count(key('category-by-code', @code)/../../cat:items/cat:item[@category = current()/@code])"/>
      <r:name>
        <xsl:value-of select="cat:name"/>
      </r:name>
      <xsl:if test="cat:description">
        <r:description>
          <xsl:apply-templates select="cat:description/node()" mode="summary"/>
        </r:description>
      </xsl:if>
    </r:category>
  </xsl:template>

  <xsl:template match="cat:item" mode="detail">
    <r:item id="{@id}" category="{@category}">
      <xsl:attribute name="position" select="position()"/>
      <xsl:attribute name="price" select="f:display-price(.)"/>

      <r:name>
        <xsl:value-of select="normalize-space(cat:name)"/>
      </r:name>

      <xsl:choose>
        <xsl:when test="@stock castable as xs:integer and xs:integer(@stock) gt 0">
          <r:availability status="in-stock">
            <xsl:value-of select="@stock"/>
          </r:availability>
        </xsl:when>
        <xsl:when test="@discontinued = 'true'">
          <r:availability status="discontinued"/>
        </xsl:when>
        <xsl:otherwise>
          <r:availability status="back-order"/>
        </xsl:otherwise>
      </xsl:choose>

      <xsl:if test="cat:tags/cat:tag">
        <r:tags>
          <xsl:for-each select="cat:tags/cat:tag">
            <r:tag index="{position()}">
              <xsl:value-of select="."/>
            </r:tag>
          </xsl:for-each>
        </r:tags>
      </xsl:if>

      <xsl:where-populated>
        <r:references>
          <xsl:for-each select="cat:related/@ref">
            <xsl:variable name="target" select="key('item-by-id', .)"/>
            <xsl:if test="$target">
              <r:reference id="{.}" name="{$target/cat:name}"/>
            </xsl:if>
          </xsl:for-each>
        </r:references>
      </xsl:where-populated>

      <r:description>
        <xsl:apply-templates select="cat:description/node()" mode="summary"/>
      </r:description>

      <xsl:try>
        <r:normalized-price>
          <xsl:value-of select="xs:decimal(@price) div 100"/>
        </r:normalized-price>
        <xsl:catch errors="*">
          <r:normalized-price error="{$err:code}"
            xmlns:err="http://www.w3.org/2005/xqt-errors">0</r:normalized-price>
        </xsl:catch>
      </xsl:try>
    </r:item>
  </xsl:template>

  <xsl:template match="cat:em" mode="summary">
    <r:emphasis>
      <xsl:apply-templates mode="summary"/>
    </r:emphasis>
  </xsl:template>

  <xsl:template match="cat:code" mode="summary">
    <r:code>
      <xsl:text><![CDATA[<literal>]]></xsl:text>
      <xsl:value-of select="."/>
      <xsl:text><![CDATA[</literal>]]></xsl:text>
    </r:code>
  </xsl:template>

  <xsl:template match="text()" mode="summary">
    <xsl:value-of select="replace(., '\s+', ' ')"/>
  </xsl:template>

  <xsl:template match="processing-instruction() | comment()" mode="summary"/>

  <xsl:template name="diagnostics">
    <xsl:message expand-text="yes">
      Processing catalog at {base-uri(/*)} with λ and 🚀
    </xsl:message>
    <xsl:iterate select="1 to 3">
      <xsl:param name="checksum" select="0"/>
      <xsl:on-completion select="$checksum"/>
      <xsl:next-iteration>
        <xsl:with-param name="checksum" select="$checksum + ."/>
      </xsl:next-iteration>
    </xsl:iterate>
  </xsl:template>

  <!-- The final stylesheet element closes the complete XML document. -->
</xsl:stylesheet>
