/*
 * Syntaxmate C API. SPDX-License-Identifier: MIT
 *
 * Status-returning functions return SM_OK (0) or an sm_status error code and
 * report detail through sm_last_error_message(). Text inputs are UTF-8
 * (pointer, length) pairs and need not be NUL-terminated. Everything the
 * library returns is freed with the matching sm_*_free function.
 */

#ifndef SYNTAXMATE_H
#define SYNTAXMATE_H

/* Generated by cbindgen from src/lib.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Value of `sm_style.foreground` / `sm_style.background` when the color is absent.
#define SM_NO_COLOR UINT32_MAX

// Bold bit in `sm_style.modifiers`.
#define SM_BOLD 1

// Italic bit in `sm_style.modifiers`.
#define SM_ITALIC 2

// Underline bit in `sm_style.modifiers`.
#define SM_UNDERLINE 4

// Strikethrough bit in `sm_style.modifiers`.
#define SM_STRIKETHROUGH 8

// Result of every fallible `sm_` function. `SM_OK` is zero; other values
// are stable and never renumbered. Read `sm_last_error_message` for detail.
enum sm_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Success.
  SM_OK = 0,
  // The language ID or alias is not in the catalog.
  SM_UNKNOWN_LANGUAGE = 1,
  // The bundled theme name is unknown.
  SM_UNKNOWN_THEME = 2,
  // A grammar could not be parsed or prepared.
  SM_INVALID_GRAMMAR = 3,
  // A custom theme could not be parsed.
  SM_INVALID_THEME = 4,
  // A grammar bundle could not be decoded.
  SM_INVALID_BUNDLE = 5,
  // A null pointer, invalid UTF-8, an out-of-range value, or other rejected input.
  SM_INVALID_INPUT = 6,
  // Output rendering failed.
  SM_RENDER = 7,
  // An unexpected internal failure, including a caught Rust panic.
  SM_INTERNAL = 8,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum sm_status sm_status;
#else
typedef uint32_t sm_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// Unit of every offset and length in a token buffer.
enum sm_offset_unit
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // UTF-8 bytes (the default for C and C++).
  SM_OFFSET_UTF8 = 0,
  // UTF-16 code units.
  SM_OFFSET_UTF16 = 1,
  // Unicode scalar values.
  SM_OFFSET_CODE_POINT = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum sm_offset_unit sm_offset_unit;
#else
typedef uint32_t sm_offset_unit;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A grammar catalog and highlighter. Immutable and safe to share across
// threads; free once with `sm_engine_free` after all users finish.
typedef struct sm_engine sm_engine;

// An incremental highlighting session. Not thread-safe: use one session
// from one thread at a time. It does not borrow the engine or theme it was
// created from, which may be freed first.
typedef struct sm_session sm_session;

// An owned UTF-8 string. It may contain interior NUL bytes (for example
// ANSI output with sanitization disabled), so use `sm_string_len`.
typedef struct sm_string sm_string;

// An owned list of strings.
typedef struct sm_string_list sm_string_list;

// A bundled or custom theme. Immutable and safe to share across threads.
typedef struct sm_theme sm_theme;

// An owned token buffer; read it with `sm_tokens_view`.
typedef struct sm_tokens sm_tokens;

// Options for `sm_engine_tokens` and `sm_engine_session`.
typedef struct {
  // An `sm_offset_unit` value; others fail with `SM_INVALID_INPUT`.
  uint32_t unit;
  // Fill `sm_token_view.token_scopes` and the scope stacks.
  bool include_scopes;
} sm_token_options;

// Options for `sm_engine_html`. Strings are (pointer, length) pairs; a NULL
// pointer means "absent".
typedef struct {
  // Wrap output in `<pre><code>…</code></pre>`.
  bool include_wrapper;
  // Add a `data-scopes` attribute with each token's scope stack.
  bool include_scopes;
  // Class on the `<pre>` wrapper (default `"syntaxmate"`); NULL for none.
  const char *wrapper_class;
  // Length of `wrapper_class` in bytes.
  size_t wrapper_class_len;
  // Emit scope classes with this prefix instead of inline styles; NULL for
  // inline styles. Pair with `sm_theme_stylesheet` using the same prefix.
  const char *class_prefix;
  // Length of `class_prefix` in bytes.
  size_t class_prefix_len;
} sm_html_options;

// Options for `sm_engine_ansi`.
typedef struct {
  // Emit 24-bit color and modifier SGR sequences.
  bool colors;
  // Replace control characters in the source with visible control pictures.
  // Keep enabled for untrusted input.
  bool sanitize_control_characters;
  // Paint the theme's default background.
  bool include_default_background;
} sm_ansi_options;

// A borrowed UTF-8 string: `len` bytes at `ptr`, followed by a NUL byte.
// `ptr` is NULL only where a function documents an absent value.
typedef struct {
  // First byte; `ptr[len]` is NUL.
  const char *ptr;
  // Length in bytes, excluding the NUL.
  size_t len;
} sm_str;

// A resolved style.
typedef struct {
  // `0xRRGGBB`, or `SM_NO_COLOR`.
  uint32_t foreground;
  // `0xRRGGBB`, or `SM_NO_COLOR`.
  uint32_t background;
  // Bitset of `SM_BOLD`, `SM_ITALIC`, `SM_UNDERLINE`, `SM_STRIKETHROUGH`.
  uint32_t modifiers;
} sm_style;

// Borrowed flat arrays of an `sm_tokens` buffer, valid until it is freed.
//
// Lines split on `\n` only. Token `i` covers
// `[token_starts[i], token_starts[i] + token_lengths[i])` in `unit`s of the
// whole input (a session buffer covers one line). Tokens of line `l` are
// indices `[line_token_ranges[l], line_token_ranges[l + 1])`. Text outside
// every token uses `default_style`. Array pointers are non-NULL even when
// their count is zero, except `token_scopes`.
typedef struct {
  // The `sm_offset_unit` of every offset and length.
  uint32_t unit;
  // False if tokenization stopped at a resource limit.
  bool complete;
  // Number of logical lines.
  size_t line_count;
  // `line_count` offsets of each line's first character.
  const uint32_t *line_starts;
  // `line_count + 1` token index boundaries.
  const uint32_t *line_token_ranges;
  // Number of tokens.
  size_t token_count;
  // `token_count` start offsets.
  const uint32_t *token_starts;
  // `token_count` lengths.
  const uint32_t *token_lengths;
  // `token_count` indices into `styles`.
  const uint32_t *token_styles;
  // `token_count` indices into the scope stacks; NULL when scopes were not
  // requested or there are no tokens.
  const uint32_t *token_scopes;
  // Number of distinct styles.
  size_t style_count;
  // `style_count` styles.
  const sm_style *styles;
  // Number of distinct scope stacks; read them with `sm_tokens_scope_stack`.
  size_t scope_stack_count;
  // The theme's default foreground and background.
  sm_style default_style;
} sm_token_view;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the library version as a static NUL-terminated string.
const char *sm_version(void);

// Returns the message of the last failed `sm_` call on the calling thread,
// or NULL if the last status-returning call succeeded. The NUL-terminated
// message stays valid until the next `sm_` call on this thread that returns
// `sm_status`. Error detail is thread-local, so concurrent callers never see
// each other's messages.
const char *sm_last_error_message(void);

// Default token options: UTF-8 offsets, no scopes.
sm_token_options sm_token_options_default(void);

// Default HTML options: wrapper with class `"syntaxmate"`, inline styles.
sm_html_options sm_html_options_default(void);

// Default ANSI options: colors on, control characters sanitized.
sm_ansi_options sm_ansi_options_default(void);

// Returns the bytes of `string`, followed by a NUL; NULL if `string` is NULL.
//
// # Safety
// `string` is NULL or a live `sm_string`.
const char *sm_string_data(const sm_string *string);

// Returns the length of `string` in bytes, excluding the NUL; 0 if NULL.
//
// # Safety
// `string` is NULL or a live `sm_string`.
size_t sm_string_len(const sm_string *string);

// Frees a string. NULL is ignored.
//
// # Safety
// `string` is NULL or an `sm_string` not yet freed.
void sm_string_free(sm_string *string);

// Returns the number of strings in `list`; 0 if NULL.
//
// # Safety
// `list` is NULL or a live `sm_string_list`.
size_t sm_string_list_len(const sm_string_list *list);

// Returns string `index` of `list`, borrowed until the list is freed;
// `{NULL, 0}` if `list` is NULL or `index` is out of range.
//
// # Safety
// `list` is NULL or a live `sm_string_list`.
sm_str sm_string_list_get(const sm_string_list *list, size_t index);

// Frees a string list. NULL is ignored.
//
// # Safety
// `list` is NULL or an `sm_string_list` not yet freed.
void sm_string_list_free(sm_string_list *list);

// Creates an engine over the embedded grammar catalog. Fails with
// `SM_INVALID_INPUT` if the library was built without bundled grammars.
//
// # Safety
// `out` is NULL or valid for writes.
sm_status sm_engine_bundled(sm_engine **out);

// Creates an engine from grammar-bundle bytes. The bytes are copied.
//
// # Safety
// `bytes` is valid for `len` bytes (or `len` is 0); `out` is NULL or writable.
sm_status sm_engine_from_bundle(const uint8_t *bytes, size_t len, sm_engine **out);

// Frees an engine. NULL is ignored. Sessions, themes, and buffers created
// from it stay valid.
//
// # Safety
// `engine` is NULL or an `sm_engine` not yet freed and no longer in use.
void sm_engine_free(sm_engine *engine);

// Lists canonical language IDs.
//
// # Safety
// `engine` is NULL or live; `out` is NULL or writable.
sm_status sm_engine_languages(const sm_engine *engine, sm_string_list **out);

// Lists bundled theme names.
//
// # Safety
// `engine` is NULL or live; `out` is NULL or writable.
sm_status sm_engine_themes(const sm_engine *engine, sm_string_list **out);

// Resolves a language ID or alias. On success `*out` is the canonical ID, or
// NULL if the language is unknown.
//
// # Safety
// `language` is valid for `language_len` bytes; `engine` is NULL or live;
// `out` is NULL or writable.
sm_status sm_engine_canonical_language(const sm_engine *engine,
                                       const char *language,
                                       size_t language_len,
                                       sm_string **out);

// Detects a language from an optional path (NULL for none) and the source's
// first line. On success `*out` is the language ID, or NULL if undetected.
//
// # Safety
// `path` is NULL or valid for `path_len` bytes; `source` is valid for
// `source_len` bytes; `engine` is NULL or live; `out` is NULL or writable.
sm_status sm_engine_detect(const sm_engine *engine,
                           const char *path,
                           size_t path_len,
                           const char *source,
                           size_t source_len,
                           sm_string **out);

// Highlights `source` to escaped HTML. `options` may be NULL for defaults.
// `complete`, if non-NULL, receives false when tokenization stopped at a
// resource limit.
//
// # Safety
// Text pointers are valid for their lengths; handles are NULL or live;
// `options` is NULL or readable; `out` and `complete` are NULL or writable.
sm_status sm_engine_html(const sm_engine *engine,
                         const char *language,
                         size_t language_len,
                         const char *source,
                         size_t source_len,
                         const sm_theme *theme,
                         const sm_html_options *options,
                         sm_string **out,
                         bool *complete);

// Highlights `source` to 24-bit ANSI text. `options` may be NULL for
// defaults. `complete` is as for `sm_engine_html`.
//
// # Safety
// As for `sm_engine_html`.
sm_status sm_engine_ansi(const sm_engine *engine,
                         const char *language,
                         size_t language_len,
                         const char *source,
                         size_t source_len,
                         const sm_theme *theme,
                         const sm_ansi_options *options,
                         sm_string **out,
                         bool *complete);

// Highlights a whole document into a token buffer. `options` may be NULL
// for defaults (UTF-8 offsets, no scopes).
//
// # Safety
// Text pointers are valid for their lengths; handles are NULL or live;
// `options` is NULL or readable; `out` is NULL or writable.
sm_status sm_engine_tokens(const sm_engine *engine,
                           const char *language,
                           size_t language_len,
                           const char *source,
                           size_t source_len,
                           const sm_theme *theme,
                           const sm_token_options *options,
                           sm_tokens **out);

// Starts an incremental session. `options` may be NULL for defaults.
//
// # Safety
// `language` is valid for `language_len` bytes; handles are NULL or live;
// `options` is NULL or readable; `out` is NULL or writable.
sm_status sm_engine_session(const sm_engine *engine,
                            const char *language,
                            size_t language_len,
                            const sm_theme *theme,
                            const sm_token_options *options,
                            sm_session **out);

// Loads a bundled theme by name.
//
// # Safety
// `name` is valid for `name_len` bytes; `out` is NULL or writable.
sm_status sm_theme_bundled(const char *name, size_t name_len, sm_theme **out);

// Parses a TextMate JSON theme.
//
// # Safety
// `json` is valid for `json_len` bytes; `out` is NULL or writable.
sm_status sm_theme_from_json(const char *json, size_t json_len, sm_theme **out);

// Frees a theme. NULL is ignored. Sessions created with it stay valid.
//
// # Safety
// `theme` is NULL or an `sm_theme` not yet freed and no longer in use.
void sm_theme_free(sm_theme *theme);

// Returns the theme's name, borrowed until the theme is freed;
// `{NULL, 0}` if `theme` is NULL.
//
// # Safety
// `theme` is NULL or live.
sm_str sm_theme_name(const sm_theme *theme);

// Returns the theme's default foreground and background.
//
// # Safety
// `theme` is NULL or live; `out` is NULL or writable.
sm_status sm_theme_default_style(const sm_theme *theme, sm_style *out);

// Returns CSS for HTML rendered with `class_prefix` (see `sm_html_options`).
//
// # Safety
// `class_prefix` is valid for `class_prefix_len` bytes; `theme` is NULL or
// live; `out` is NULL or writable.
sm_status sm_theme_stylesheet(const sm_theme *theme,
                              const char *class_prefix,
                              size_t class_prefix_len,
                              sm_string **out);

// Highlights the next logical line, without its `\n` terminator. The
// buffer holds one line with line-relative offsets. A line containing `\n`
// fails with `SM_INVALID_INPUT`.
//
// # Safety
// `line` is valid for `line_len` bytes; `session` is NULL or live and not in
// use by another thread; `out` is NULL or writable.
sm_status sm_session_line(sm_session *session, const char *line, size_t line_len, sm_tokens **out);

// Returns the session to the start-of-document state.
//
// # Safety
// `session` is NULL or live and not in use by another thread.
sm_status sm_session_reset(sm_session *session);

// Frees a session. NULL is ignored.
//
// # Safety
// `session` is NULL or an `sm_session` not yet freed and no longer in use.
void sm_session_free(sm_session *session);

// Fills `out` with borrowed pointers into `tokens` (no copy). They stay
// valid until `sm_tokens_free`. A buffer may be read from several threads.
//
// # Safety
// `tokens` is NULL or live; `out` is NULL or writable.
sm_status sm_tokens_view(const sm_tokens *tokens, sm_token_view *out);

// Returns scope stack `index` (outermost scope first) as `*len` borrowed
// strings at `*names`, valid until `sm_tokens_free`. An out-of-range
// `index` fails with `SM_INVALID_INPUT`.
//
// # Safety
// `tokens` is NULL or live; `names` and `len` are NULL or writable.
sm_status sm_tokens_scope_stack(const sm_tokens *tokens,
                                size_t index,
                                const sm_str **names,
                                size_t *len);

// Frees a token buffer. NULL is ignored.
//
// # Safety
// `tokens` is NULL or an `sm_tokens` not yet freed and no longer in use.
void sm_tokens_free(sm_tokens *tokens);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SYNTAXMATE_H */
