-- SQL stress fixture: portable core with PostgreSQL-flavored edges.
-- Unicode identifiers and data stay visible: café, 東京, 🚀, 𝌆.
/*
 * The statements are intentionally independent enough for syntax review.
 * This file stresses multiline lexical state while remaining closed at EOF.
 */
-- Schema, types, and relational DDL -----------------------------------------
CREATE SCHEMA IF NOT EXISTS "Research 🚀";
SET search_path TO "Research 🚀", public;
CREATE DOMAIN positive_amount AS NUMERIC(14, 2) CHECK (VALUE >= 0.00);
CREATE TYPE task_state AS ENUM (
    'queued', 'running',
    'done', 'blocked'
);
CREATE TABLE "Team" (
    team_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "display name" VARCHAR(120) NOT NULL,
    region CHAR(2) DEFAULT 'EU', created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT team_name_unique UNIQUE ("display name")
);
CREATE TABLE project (
    project_id UUID PRIMARY KEY,
    team_id BIGINT NOT NULL REFERENCES "Team" (team_id),
    code TEXT COLLATE "C" NOT NULL,
    budget positive_amount,
    metadata JSONB DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    starts_on DATE, ends_on DATE,
    EXCLUDE USING gist (code WITH =),
    CHECK (ends_on IS NULL OR ends_on >= starts_on)
);
CREATE TABLE task (
    task_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    project_id UUID NOT NULL,
    parent_id INTEGER, title TEXT NOT NULL,
    state task_state DEFAULT 'queued', estimate INTERVAL,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    payload BYTEA, score DOUBLE PRECISION,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (task_id),
    FOREIGN KEY (project_id) REFERENCES project (project_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES task (task_id)
        DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE task
    ADD COLUMN owner_name TEXT, ALTER COLUMN title SET STORAGE EXTENDED;
COMMENT ON COLUMN task.payload IS 'Opaque bytes; may begin with \x00';
CREATE TABLE stage_task
    (LIKE task INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
-- Literals, quoting, and data modification ---------------------------------
INSERT INTO "Team" ("display name", region)
VALUES ('Café λ', 'FR'),
       ('東京 🚀', 'JP'),
       ('Quote ''keepers''', DEFAULT)
ON CONFLICT ("display name") DO UPDATE
SET region = EXCLUDED.region
RETURNING team_id, "display name" AS "label 𝌆";
INSERT INTO project (project_id, team_id, code, budget, metadata, starts_on)
SELECT '123e4567-e89b-12d3-a456-426614174000'::uuid,
       t.team_id, E'rocket\nlab',
       1_024.50, '{"mission":"🚀","ok":true}'::jsonb,
       DATE '2025-01-20'
FROM "Team" AS t
WHERE t."display name" = U&'Caf\00E9 \03BB';
INSERT INTO task (project_id, title, state, estimate, tags, score)
VALUES
    ('123e4567-e89b-12d3-a456-426614174000',
     'first line
second line with 𝌆',
     'running', INTERVAL '2 days 03:04:05', ARRAY['sql', 'unicode'], 6.02e23),
    ('123e4567-e89b-12d3-a456-426614174000',
     $$dollar-quoted 'task' 🚀$$,
     'queued', '90 minutes'::interval, ARRAY[]::text[], .875);
UPDATE task AS dst
SET score = COALESCE(dst.score, 0) + src.bump,
    updated_at = CURRENT_TIMESTAMP, payload = decode('DEADBEEF', 'hex')
FROM (VALUES (1, 2.5), (2, -0.25)) AS src(task_id, bump)
WHERE dst.task_id = src.task_id
  AND dst.state IS DISTINCT FROM 'done'
RETURNING dst.task_id, dst.score;
DELETE FROM task
WHERE state = 'blocked'
  AND CURRENT_DATE > updated_at + INTERVAL '30 days'
RETURNING task_id;
MERGE INTO stage_task AS target
USING task AS source ON target.task_id = source.task_id
WHEN MATCHED AND source.updated_at > target.updated_at THEN
    UPDATE SET title = source.title, state = source.state
WHEN NOT MATCHED THEN
    INSERT (task_id, project_id, title, state)
    VALUES (source.task_id, source.project_id, source.title, source.state);
-- CTEs, recursion, windows, FILTER, and set operations ---------------------
WITH RECURSIVE tree AS (
    SELECT t.task_id, t.parent_id, t.title, 0 AS depth,
           ARRAY[t.task_id] AS path
    FROM task AS t WHERE t.parent_id IS NULL
  UNION ALL
    SELECT child.task_id, child.parent_id, child.title, tree.depth + 1,
           tree.path || child.task_id
    FROM task AS child
    JOIN tree ON tree.task_id = child.parent_id
    WHERE NOT child.task_id = ANY (tree.path)
), ranked AS MATERIALIZED (
    SELECT tree.*,
           row_number() OVER named_window AS ordinal,
           count(*) FILTER (WHERE depth > 1) OVER () AS deep_count,
           lag(title, 1, '∅') OVER named_window AS previous_title
    FROM tree
    WINDOW named_window AS (
        PARTITION BY parent_id ORDER BY depth, task_id
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )
)
SELECT depth, ordinal, title, previous_title, deep_count
FROM ranked
WHERE 3 >= ordinal
UNION ALL
SELECT -1, 0, 'no tasks', NULL, 0
WHERE NOT EXISTS (SELECT 1 FROM ranked)
ORDER BY depth NULLS LAST, ordinal
FETCH FIRST 20 ROWS WITH TIES;
-- Joins, subqueries, grouping, CASE, casts, and operators ------------------
SELECT p.code,
       CASE
           WHEN p.budget IS NULL THEN 'unknown'
           WHEN p.budget BETWEEN 0 AND 999.99 THEN 'small'
           ELSE 'large'
       END::varchar(16) AS budget_band,
       (SELECT max(x.value)
          FROM unnest(ARRAY[1, 3, 2]) AS x(value)) AS local_max,
       stats.open_count,
       p.metadata ->> 'mission' AS mission
FROM project AS p
INNER JOIN "Team" AS tm USING (team_id)
LEFT OUTER JOIN LATERAL (
    SELECT count(*) FILTER (WHERE t.state IS DISTINCT FROM 'done') AS open_count
    FROM task AS t
    WHERE t.project_id = p.project_id
) AS stats ON TRUE
FULL JOIN (SELECT DISTINCT project_id FROM task) AS seen
    ON seen.project_id = p.project_id
WHERE (p.active AND p.code ILIKE '%lab%' ESCAPE '\')
   OR p.project_id IN (SELECT project_id FROM task WHERE score >= 0x10)
GROUP BY p.project_id, p.code, p.budget, p.metadata, stats.open_count
HAVING count(*) >= 1;
SELECT CAST('NaN' AS DOUBLE PRECISION) AS not_a_number,
       0b1010 + 0o17 + 0x2A AS mixed_radices, B'101001' AS bits,
       X'CAFE' AS hex_bytes, TRUE AND NOT FALSE AS logic_value,
       7 % 4 AS remainder, 2 ^ 8 AS power_value,
       'abc' SIMILAR TO '(a|b)%' AS pattern_match;
-- Transactions, prepared statements, views, and indexes -------------------
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ WRITE;
SAVEPOINT before_adjustment;
SET CONSTRAINTS ALL DEFERRED;
UPDATE project SET budget = budget * 1.05 WHERE active;
ROLLBACK TO SAVEPOINT before_adjustment;
RELEASE SAVEPOINT before_adjustment;
COMMIT AND CHAIN;
ROLLBACK;
PREPARE lookup_task (integer, task_state) AS
    SELECT task_id, title FROM task
    WHERE task_id >= $1 AND state = $2;
EXECUTE lookup_task(10, 'queued');
DEALLOCATE lookup_task;
CREATE OR REPLACE VIEW active_project_summary
    (project_id, code, task_count) AS
SELECT p.project_id, p.code, count(t.task_id)
FROM project AS p
LEFT JOIN task AS t ON t.project_id = p.project_id
WHERE p.active
GROUP BY p.project_id, p.code
WITH LOCAL CHECK OPTION;
CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS project_code_lower_idx
    ON project (lower(code) ASC NULLS LAST)
    INCLUDE (team_id)
    WHERE active IS TRUE;
-- PostgreSQL procedural bodies and multiline dollar-quoted state ----------
CREATE OR REPLACE FUNCTION bump_task_score(p_task_id integer, p_delta numeric)
RETURNS numeric LANGUAGE plpgsql SECURITY INVOKER
AS $score_body$
DECLARE
    result numeric;
BEGIN
    UPDATE task
       SET score = COALESCE(score, 0) + p_delta
     WHERE task_id = p_task_id
     RETURNING score INTO STRICT result;
    IF 0 > result THEN
        RAISE EXCEPTION 'negative score for task %', p_task_id
            USING HINT = 'Pass a non-negative delta 🚀';
    ELSIF result = 0 THEN
        RAISE NOTICE 'task % remains neutral', p_task_id;
    END IF;
    RETURN result;
END;
$score_body$;
DO $maintenance$
BEGIN
    PERFORM 1 FROM task WHERE title LIKE '%𝌆%';
    /* Dollar bodies may contain semicolons and quote marks: ';' and "x". */
END;
$maintenance$;
-- Administration and a deliberately calm, fully closed EOF ----------------
GRANT SELECT, INSERT, UPDATE ON task TO PUBLIC;
REVOKE UPDATE (payload) ON task FROM PUBLIC;
ANALYZE VERBOSE task (state, updated_at);
/* Final multiline comment:
   every quote, parenthesis, comment, and dollar delimiter above is closed. */
